on:
  push:
    branches:
      - master
    paths:
      - 'frontend_comisarias/**'
env:
  COMPONENT_NAME: 'frontend_comisarias'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
      options: --user root
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i --prefix ./$COMPONENT_NAME/

      - name: Run Tests
        run: npm test --prefix ./$COMPONENT_NAME/

      - name: Build
        run: npm run build:prod --prefix ./$COMPONENT_NAME/

      - name: Deploy
        if: success()
        run: aws s3 ls

