on:
  push:
    branches:
      - master
    paths:
      - 'ms_protection_measure/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x ms_protection_measure/gradlew
      - name: Unit test
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.JAVA_ACTOR }}
        run: ./ms_protection_measure/gradlew -p ms_protection_measure clean build jacocoMergedReport
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./ms_protection_measure/gradlew build sonarqube --info
        with:
          build-root-directory: ms_protection_measure